### ISSUE TITLE
Docker build fails due to missing file

### ISSUE THREAD

**Issue by JoelB** [agrifooddatacanada/OCA_browser#2]
The Docker build of this repo fails due to a missing file ../assets/oca_overlays.png referenced here:

https://github.com/agrifooddatacanada/OCA_browser/blame/4d355f1af44055400cbf2fe87e1420f100562d5c/src/pages/About.vue#L77

Doing 'mkdir src/assets && touch src/assets/oca_overlays.png' creates a dummy file that allows the build to succeed.

**Comment by xingjian-xu** [comment]
Uploaded the missing image [oca_overlays.png](https://github.com/agrifooddatacanada/OCA_browser/blob/main/src/assets/oca_overlays.png).
